### ISSUE TITLE
Link not accessible to user?

### ISSUE THREAD

**Issue by daniel-barrows** [rafspiny/jsondiff#17]
I installed this add-on, and then couldn't figure out how to access it. I looked at the github page, the firefox add-on page, the Firefox tools menu, and my Firefox addons list. I eventually just zoomed in on the screenshot to discover it is accessible at resource://jsondiff/data/html/panel.html. I would recommend placing this link on all of these places.

**Comment by daniel-barrows** [comment]
I now see that there is a new toolbar icon to access this. However, I still think links in other places would be helpful. Besides, I would much rather just bookmark the link or access it through the Tools menu and not have a toolbar button.

**Comment by rafspiny** [comment]
Closing because of #18
