### ISSUE TITLE
This repo is used by malware

### ISSUE THREAD

**Issue by Cxarli** [rafspiny/jsondiff#28]
A malicious extension for Firefox is spread over the internet, which uses this repo to disguise itself. It was found at extgotype[DOT]cool/3/pending/  (**MALWARE**, only works on Firefox)  and I made a video which shows how it installs itself which can be found here: https://files.fm/u/jm2uajex . The modified extension can be downloaded for inspection via this link: https://files.fm/u/5bvfuk6b

I know this isn't an issue you can solve, but it would be nice if you could put a warning in the README file stating that if someone suddenly has an extension with a link to this repo, it could be malicious.

**Comment by rafspiny** [comment]
Thanks for letting me know. You claim that the malware is spread, it would be nice to provide some cases.
Plus, the [distribution mechanism](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/Distribution) makes **slighty difficult** to install addons not coming from the marketplace. 
I admit that I ignore how InstallTrigger handles signatures, but I would believe that the distribution policy is still valid.
Nevertheless, I believe the best thing to do is to report the website, like at [https://safebrowsing.google.com/safebrowsing/report_badware/](https://safebrowsing.google.com/safebrowsing/report_badware/) as I have already done.

in general: [how to report malicious websites)[https://security.stackexchange.com/questions/1728/where-to-report-malicious-urls-phishing-and-malicious-web-sites]

Thanks for letting me know.

P.S.: pretty fast finding: [https://whois.icann.org/en/lookup?name=extgotype.cool](https://whois.icann.org/en/lookup?name=extgotype.cool)
